### ISSUE TITLE
目录结构规范化

### ISSUE THREAD

**Issue by pedia** [finlutter/flutter_fintech_widgets#6]
两种方案

1 按业务分，譬如 stock, 资讯， 每个业务一个目录
2 按 pages/models 分

vote in comment.

**Comment by dozenlue** [comment]
Could be covered by #8

**Comment by pedia** [comment]
- 感觉 candlestick 等功能每个都应该相对独立、内聚，便于直接使用和拆过去使用
- 感觉项目应该是 lib，然后 examples 里有多个 app，然后还有个控件列表
- Redux 并不能解决这些问题和期望 @dozenlue
