### ISSUE TITLE
引入Redux或FishRedux

### ISSUE THREAD

**Issue by dozenlue** [finlutter/flutter_fintech_widgets#8]

**Comment by pedia** [comment]
如果定位为 xx widgets，就是这些 widgets 能比较容易的使用，如果在不是必须时就引入一个重框架，势必会增加使用上的不便。
Redux 等都太重了

**Comment by pedia** [comment]
局部引入，建议比较后再行定夺，是否全局依赖之

**Comment by pedia** [comment]
你也说不需要了，close it
